# Funding configuration for GitHub Sponsor button
# Replace placeholder links below with your real links.

custom:
  - "https://ko-fi.com/uberdudepl"
  - "https://paypal.me/uberdudepl"
  - "https://revolut.me/uberdudepl"
